[package]
name = "ddns-my-public-ip"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
reqwest = { version = "0.12", features = ["charset", "http2", "blocking", "rustls-tls-webpki-roots"], default-features = false }
